import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import './globals.css';

export const metadata = {
  title: "Les papillons énergétiques",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <main>{children}</main> 
        <Footer />
      </body>
    </html>
  );
}
